# Fix depedencies issues: remove docker package & `conda config --add channels conda-forge`
# conda create --name conda_build_env python=3.6
# conda activate conda_build_env
# conda install conda-build anaconda-client
# conda skeleton pypi substra & mv meta file at the root of the repo
# conda config --set anaconda_upload no
# conda-build .
# when ready: conda config --set anaconda_upload yes
# src: https://btrdb.readthedocs.io/en/latest/maintainers/anaconda.html


{% set name = "mplc" %}
{% set version = "0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .
  # url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  # sha256: ea4b614c8cca196a8ed64ec7f069d38ba9c4ca76b5834bec1ae1798423ed7615

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - h5py==2.10.0
    - joblib==0.15.1
    - librosa==0.8.0
    - Keras==2.3.1
    - matplotlib==3.1.3
    - numpy==1.18.5
    - scipy==1.4.1
    - scikit-learn==0.22.1
    - pandas==1.0.5
    - seaborn==0.10.0
    - loguru==0.4.1
    - tensorflow==2.2.0
    - ruamel.yaml==0.16.10
 
  run:
    - python
    - h5py==2.10.0
    - joblib==0.15.1
    - librosa==0.8.0
    - Keras==2.3.1
    - matplotlib==3.1.3
    - numpy==1.18.5
    - scipy==1.4.1
    - scikit-learn==0.22.1
    - pandas==1.0.5
    - seaborn==0.10.0
    - loguru==0.4.1
    - tensorflow==2.2.0
    - ruamel.yaml==0.16.10

test:
  imports:
    - mplc

about:
  home: https://github.com/SubstraFoundation/distributed-learning-contributivity 
  license: Apache 2.0
  license_family: APACHE
  license_file: 
  summary: "MPLC"
  doc_url: 
  dev_url: 

